### ISSUE TITLE
Not compliant with 'Google C++ Style Guide'

### ISSUE THREAD

**Issue by trygveu** [drmikehenry/vim-headerguard#2]
First off, thank you for a very nice solution to the header guards! It is greatly appreciated.

The [Google C++ Style guide](http://google.github.io/styleguide/cppguide.html#The__define_Guard) has a point that the include guard should be based off the full project path of the file, to reduce the chance of name collision. This does result in very long include guards, which many probably wont like, others might. It's part of the default check for [cpplint.py](https://github.com/google/styleguide/tree/gh-pages/cpplint), which leads me to seeking compliance.

To do this, Vim needs to be aware of the project structure to find the root. I don't know what would be the best way to do this. Some ideas are: 
- look for the .git file
- check CMakeLists for the project name

It's a too big task to do this for all build systems, but maybe we could do it for git repositories?
What do you think? How would you solve it, and do you consider it worth the effort?

**Comment by drmikehenry** [comment]
It's an interesting idea.  Finding the root of a source-controlled tree in an arbitrary source control system can be complicated.  Something like that deserves to live in a separate plugin.  I use a couple of plugins that internally have some functions to handle this, but I haven't had the time to look around for a library implementation that would expose the feature directly.  VCSCommand (http://www.vim.org/scripts/script.php?script_id=90) understands many VCS systems and probably contains logic you could extract to determine the root of a repository for a given file path.  Fugitive (git://github.com/tpope/vim-fugitive.git) has good support for just Git if that's all you'd need, and there's probably some functionality you could lift from that plugin.  I'm not sure if either plugin would expose exactly the right function so you could simply call it (rather than extract the source code of the plugin into your own `.vimrc`).

Once having a function to determine the root directory, you'd use that function in an overridden definition of `g:HeaderguardName()` to use this function to compute the desired guard name.

There's a simpler approach you might try if you are willing to redefine the problem slightly.  If you always maintain the current working directory to be the root of your project, then the below function will calculate the guard name using the header file's path relative to CWD:

``` VimL
function! g:HeaderguardName()
    return toupper(expand('%:.:gs/[^0-9a-zA-Z_]/_/g')) . '_'
endfunction
```

It works by using `%:.` to get the header path relative to CWD.  If that restriction isn't too limiting for you, it's easy to try it out and see how you like it.

I'm sorry I don't have more time to dedicate to this.  For my own needs, I've wanted a function that returns the path to a file's repository, but I haven't spent the effort to find (or create) such a function.

Michael Henry

**Comment by trygveu** [comment]
Hi Michael, thank you very much. I usually run vim out of the root of the repo, so that works perfectly for me.

There are two more issues to change for cpplint.py to pass:

use: `let g:headerguard_use_cpp_comments = '1'`
And a minor change in plugin/headerguard.vim:46 to add two spaces between `#endif` and `//`.
`return "#endif  // " . s:Func('Name')()`

It solves my problem, so we shouldn't spend more time on it. Thanks for the quick reply!

**Comment by drmikehenry** [comment]
Hi, Trygve,

I hadn't noticed the need for the extra space in Google's style guide.  It's possible to change the plugin's behavior by overriding most of the functions.  For most script-local functions in the plugin, such as this one:

``` VimL
function! s:HeaderguardLine3()
    if g:headerguard_use_cpp_comments
        return "#endif // " . s:Func('Name')()
    else
        return "#endif /* " . s:Func('Name')() . " */"
    endif
endfunction
```

You can provide a global function that overrides the behavior.  Just replace the `s:` prefix with `g:` in your `.vimrc` and change the behavior as desired.  Since you are always interested in using C++-style comments, you can simplify the function a bit to ignore `g:headerguard_use_cpp_comments`, which means you won't need to set that variable anymore.

``` VimL
function! g:HeaderguardLine3()
    return "#endif  // " . g:HeaderguardName()
endfunction
```

Combined with your definition for `g:HeaderguardName()`, this should be all you need to match the Google style guide without patching the plugin.

**Comment by timakro** [comment]
For anyone coming here in the future, if your source directory is called `src` this will do it for you:

```
function! g:HeaderguardName()
    return toupper(expand('%:p:s@^.*/src/\(.*\)$@\1@:gs/[^0-9a-zA-Z_]/_/'))
endfunction
```

The header for a file `src/engine/server.h` will then be called `ENGINE_SERVER_H`, regardless of your working directory.
